### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by Kroid** [spencermountain/nlp_compromise#17]
Amazing library, thanks guy!
Please, add your lib to bower registry http://bower.io/ http://bower.io/docs/creating-packages/

**Comment by spencermountain** [comment]
thanks george. I've added a bower package at the current version as 'nlp_compromise', but am not quite sure what i'm doing. can you check it out?
`bower info nlp_compromise`
cheers

**Comment by Kroid** [comment]
I'm fixed path in bower.json - https://github.com/spencermountain/nlp_compromise/pull/19
