### ISSUE TITLE
Sentence boundary detection.

### ISSUE THREAD

**Issue by kannanth** [spencermountain/nlp_compromise#23]
Very nice library. 

When playing with some text pulled from a web article, noticed that the sentence boundary does not always work.

For example, the text below does not split sentences correctly.

The man who tried to kill former Pope John Paul II 33 years ago showed up at the Vatican on Saturday to put white roses on his tomb and said he wanted to meet Pope Francis.Mehmet Ali Agca, a Turk, left John Paul critically injured after firing several shots in the failed assassination attempt in St. Peter's Square on May 13, 1981.The former pope forgave Agca, once a member of a Turkish far right group known as the Grey Wolves, and went to meet him in 1983 in the Rome prison where he had been sentenced to life imprisonment for the attack.Agca called the Italian daily la Repubblica on Saturday to announce he had arrived in the Vatican, his first visit since the assassination attempt and exactly 31 years after John Paul met him in prison.The visit was confirmed to Reuters by Father Ciro Benedettini, the Vatican's deputy spokesman, who said Agca stood for a few moments in silent meditation over the tomb in St. Peter's Basilica before leaving two bunches of white roses.Agca, 56, was pardoned by Italy in 2000 and extradited to Turkey where he was imprisoned for the 1979 murder of a journalist and other crimes. He was released from jail in 2010.The attack against John Paul, who died in 2005, has remained clouded by unanswered questions over who may have been behind it. An Italian investigative parliamentary commission said in 2006 it was "beyond reasonable doubt" that it was masterminded by leaders of the former Soviet Union.The Vatican on Saturday gave a cool response to Agca's request to meet with Pope Francis. "He has put his flowers on John Paul's tomb; I think that is enough," Vatican spokesman father Federico Lombardi told la Repubblica.

**Comment by spencermountain** [comment]
hey kannanth, thanks for the feedback.
there is no space after the periods of many of those sentences. That's expected for a proper sentence boundary, and i think it would be hard to support otherwise. Does it work to your liking if it has the space after the periods? That's a grammatical requirement, in my opinion.
cheers

**Comment by kannanth** [comment]
Yes, it works fine if it has the space after the periods. I think a certain
level of normalization is required before invoking the library.

I think you can close out the issue!!.

On Tue, Mar 3, 2015 at 9:29 AM, spencer kelly <notifications@github.com>
wrote:

> hey kannanth, thanks for the feedback.
> there is no space after the periods of many of those sentences. That's
> expected for a proper sentence boundary, and i think it would be hard to
> support otherwise. Does it work to your liking if it has the space after
> the periods? That's a grammatical requirement, in my opinion.
> cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spencermountain/nlp_compromise/issues/23#issuecomment-76966779>
> .
>



-- 
Best Regards
Kannan Thiagarajan
