### ISSUE TITLE
Sentence negate will negate everything

### ISSUE THREAD

**Issue by chinuy** [spencermountain/nlp_compromise#24]
for example:
[Orig]
They are based on different physical effects use to guarantee a stable grasping between a gripper and the object to be grasped.

[negate]
They are **not** based on different physical **didn't** effects use to **doesn't** guarantee a stable grasping between a gripper and the object to be grasped.

Maybe just negate the first verb would be sufficient.

**Comment by spencermountain** [comment]
hey nick, I agree. this feature needs more work, though i believe it could be very cool.
the first-verb idea is a good one, do you have examples of when that idea works and when it doesn't?
what would be good is to make a huge test-set of proper negations of different types of sentences, wanna help? what's your use-case?

**Comment by chinuy** [comment]
My use case is to falsify a sentence to confuse people from picking the correct one.

negating the first verb is an easy move. I think this should be done by verb priority weighting. I don't have curated testing set, but I absolutely can generate a bunch by processing articles.

I am glad to help!!

**Comment by spencermountain** [comment]
very cool. I will have a crack at fixing it this weekend, and shoot it back at you this monday.
cheers!

**Comment by spencermountain** [comment]
hey man, 0.3.5 has a re-write of this method, and it is much better. Passes 50 tests.
lemme know which issues you run into. I know two already, but see if you can find them ;)
-spence

**Comment by chinuy** [comment]
It is excellent!! I will try more testing case and report to you if I find anything interesting.

**Comment by spencermountain** [comment]
thanks
