### ISSUE TITLE
Adding new Names for recognition using spot?

### ISSUE THREAD

**Issue by alistairpaul** [spencermountain/nlp_compromise#28]
I looked through a variety of files, but haven't found either a list or a method of where I can append known people/organization names for recognition using .spot -- does this exist and I'm just missing it?

**Comment by spencermountain** [comment]
hey alistair, if you know what you're looking for, sounds like you may be interested in this library instead.
https://github.com/spencermountain/my_word
cheers

**Comment by alistairpaul** [comment]
I *wish* I knew what I was looking for, but I'm experimenting with parsing some resumes, and want to try to do Person Name and Organization Name recognition, so the .spot feature in nlp_compromise is what I'd like to use as a concept, but it doesn't recognize even my own name, so I attempted to find some way to append custom names to a list, sort of like training the OpenNLP model.  Thanks for the reply!

**Comment by spencermountain** [comment]
yeah, sounds tricky. maybe you could try ```nlp.pos(resumes).nouns()``` then do some kind of personal filter on it, for what you'd like as an entity. If that's not getting them, it's probably a machine-learning problem.
cheers
