### ISSUE TITLE
nlp.spot not returning entity array, but rather an object (still)

### ISSUE THREAD

**Issue by lilnate22** [spencermountain/nlp_compromise#29]
![image](https://cloud.githubusercontent.com/assets/882236/7204548/30622054-e4f1-11e4-9861-58dfff1b8455.png)

lates nlp.js from master:
![image](https://cloud.githubusercontent.com/assets/882236/7204570/64acd32c-e4f1-11e4-8c63-ba7014ad6653.png)

**Comment by lilnate22** [comment]
When words are capitalized, you get an array of objects:
![image](https://cloud.githubusercontent.com/assets/882236/7204683/37a4007a-e4f2-11e4-8b06-76bd1b0186c3.png)

**Comment by spencermountain** [comment]
hey, i've updated the documentation for this. As I've added more functionality, it's become clearer that the api should return objects for everything, then they can be flattened with .text(). Sorry for the delays.

**Comment by lilnate22** [comment]
shouldnt this still remain open?

"Joe carter loves tornto" still returns only 1 object: "joe carter"

the toronto is missing

**Comment by spencermountain** [comment]
yeah, the spotting method has become more sensitive about capitalisation, more conservative in what it considers an Entity. I've updated the Readme to show this. Thanks for your help
