### ISSUE TITLE
nlp.pos('constructor') is returning an error

### ISSUE THREAD

**Issue by scottyli** [spencermountain/nlp_compromise#33]
```
Uncaught TypeError: Cannot read property 'match' of undefined
```

```javascript
if (w.match(/^(over|under|out|-|un|re|en).{4}/)) {
  var attempt = w.replace(/^(over|under|out|.*?-|un|re|en)/, '')
  return parts_of_speech[lexicon[attempt]]
}
```

**Comment by spencermountain** [comment]
thanks scott, i will take a look

**Comment by scottyli** [comment]
Upon further investigation, it's this line https://github.com/spencermountain/nlp_compromise/blob/master/src/pos.js#L190

```contractions["constructor"]``` will return something like ```function Object() { [native code] }```

**Comment by spencermountain** [comment]
ah, this is a great one. Think i found all places where I should use hasOwnProperty, thanks a bunch. crash-test it in 0.3.10. 
cheers
