### ISSUE TITLE
Just FYI.

### ISSUE THREAD

**Issue by redaktor** [spencermountain/nlp_compromise#34]
@spencermountain 
Please see this demo http://expresso-app.org/tutorial ...
I made the same demo with your nice project.
More or less lazily by porting the "python metrics logic" to .js.
The advantages are : .js only and onKeyPress ... Think of a better http://www.hemingwayapp.com ;))
Will work on it later today. Also pointed the author of expresso to your project.

The method could either be contributed as a .metrics() function to the "root level" used in a demo or as a standalone demo. Just tell me if you are interested by writing to @redaktor (I'll close this directly) .
Thank you for starting to produce this missing javascript-puzzlepiece !

**Comment by spencermountain** [comment]
very cool stuff!
let me know if i can help with anything on this side.

**Comment by spencermountain** [comment]
an on-keypress version of either tool would be very neat, there was a guy on twitter talking about making  a text-editor plugin for something similar.

one thing we could consider is some kind of caching layer, so that each keypress only re-calculates the current sentence, or whatever. it seems redundant to parse a whole novel again at each keypress.

a challenge i'd say too, is to make something accessible to non-writer-nerds. Not everybody knows their part-of-speech vocabulary ;)
lemme see when you're done!
cheers

**Comment by redaktor** [comment]
@spencermountain Yep. Exactly.

> so that each keypress only re-calculates the current sentence, or whatever.

I thought about a ['word', 'sentence'] flag for each metrics method to show when it needs to be recalculated off course (there are a few only measured when we have enough words but before they are simply 0) .

**Comment by redaktor** [comment]
@spencermountain 
> lemme see when you're done!
I made a sneak preview in a gist:
https://gist.github.com/redaktor/e5866669e238221e7cef

The EXAMPLE.js is commented, but 
• "blacklist.js" must be placed in the ./src/data folder
• "index.js" must replace the ./index.js [to include blacklist.js as well]

The metrics which are not finished yet do all require the stemming of verb groups, either "normalized" like in
```
BVB has not been beaten by Bayern Munich.
```
or as phrasal verbs.

I have a first monster test sentence:
```
By now we could've been being served coffee on a terrace overlooking the Bay of Naples while we are looking back.
``

**Comment by spencermountain** [comment]
oh, very cool.
are you proposing this as a secondary library or a change to this current library?
I've done some refactoring of the lexicon file, and will try to add phrasal verb support, based on the examples you have in that gist. 
any ideas ie copula verb reclassification, please let me know.

I had an idea for simplifying english based on this library, which has some overlap with what you're working on, but it's too data-heavy to be included here, so I was thinking of flipping it into a second library.

**Comment by redaktor** [comment]
> any ideas ie copula verb reclassification, please let me know.
gist just updated with verb group rules. Still working on it.

However : 
> but it's too data-heavy to be included here
Do you mean in the browser ?

**Comment by spencermountain** [comment]
yeah, if you're planning on implementing new features for nlp_compromise, let me know. Things like swear-detection may not be right for this project. I'd be really supportive if you made a dependent library for this sort of thing.
Yeah, being light-weight is critical, as this is intended for the browser, mobile etc.
cheers

**Comment by redaktor** [comment]
Hm,
we are working on a huge decentralized cms. We use AMD and conditional requires allover.
That makes it lightweight (we are using http://dojotoolkit.org and their upcoming features) but I understood you want it "dependency free".
However - the metrics can be another library but see the comment
```TODO FIXME - should go to lexicon```
This should go to the main library. I am working on a german corpus in parallel.
