### ISSUE TITLE
nlp.sentences() not returning all sentences

### ISSUE THREAD

**Issue by scottyli** [spencermountain/nlp_compromise#35]
```javascript
var text = "She was dead. He was ill."
nlp.sentences(text)

// returns only ["She was dead."]
```

I think it's because of the abbreviation regex is picking up ```ill.``` as an abbreviation, rather than the end of the sentence.

https://github.com/spencermountain/nlp_compromise/blob/master/src/methods/tokenization/sentence.js#L11

Similarly, ```nlp.sentences("It was Sunday. He attended mass.")``` only returns ```["It was Sunday."]``` too

**Comment by redaktor** [comment]
@scottyli :+1: just noticed here: https://github.com/spencermountain/nlp_compromise/pull/30

> Sentences might split due to punctuation in abbreviations if those are not listed...

now we need to add the "opposite way" ;)
If a sentence ends with a (listed) abbreviation sentences might not split.


And I would like to raise another _question_ :
For negations It seems, the ```logic_negate``` object just works in one direction.
Test : "joe never swims in the pool."

Apart from that I would recommend to put the negate and abbreviation objects in the lexicon as well (which is a "resource file"). 
Separating data and logic completely would be nice for i18n, language awareness etc.

@spencermountain btw: Have you seen https://github.com/spencermountain/nlp_compromise/issues/34 - nearly finished ...

**Comment by spencermountain** [comment]
hey, thanks. yes I agree about the negative -> positive method. 
What would be the best api for that do you think? ```sentence.unNegate()```?

I've fixed the 'ill.' bug, but am gonna add a bunch more unit tests to make sure. @scottyli do you wanna add some more too?

consolidating a lot of the data is a good idea, as there are some redundant parts too. If we could reduce filesize noticably, a refactor would be worth-it, imo.
cheers

**Comment by spencermountain** [comment]
fwiw, here are the biggest data files: 
* lexicon  - 38k
* unambiguous_suffixes (very redundant) - 20k
* verb_irregulars (very redundant) - 20k
* unicode_normalisation (kinda dumb) - 13k

there are big wins to be made here, but there should be more pos tests, before we start slashing-out data

**Comment by spencermountain** [comment]
hey, i'm gonna close this, the .unNegate() will take some thinking, and most of the bigger data has found its way to the lexicon. thanks!
