### ISSUE TITLE
feature request : phrasal verbs stemming

### ISSUE THREAD

**Issue by redaktor** [spencermountain/nlp_compromise#36]
In the default mode [without ```{dont_combine:true}```] it would be nice to have phrasal verbs recognized – as they can have a totally new meaning. For example
> My grandfather likes to look back on his childhood.
```look back``

[taken from http://www.englisch-hilfen.de/grammar/phrasal_verbs.htm]

**Comment by spencermountain** [comment]
i completely agree. the actual verb is 'look back', and not 'look', like most systems do it.

lets do this.

**Comment by redaktor** [comment]
Ok, it needs to fit into the "no training environment" - so:
The best approach that  I could find after a "one day research" was the Expert Lexicon Formalism as defined in http://www.aclweb.org/anthology/P03-1065 ...

**Comment by redaktor** [comment]
:+1: for did it. Closing issue now.
