### ISSUE TITLE
Contractions

### ISSUE THREAD

**Issue by redaktor** [spencermountain/nlp_compromise#41]
Please note that ```he's```and ```she's``` becomes ```['he', 'is']``` and ```['she', 'is']```
but it could also be ```['he', 'has']``` and ```['she', 'has']```
[stackexchange](http://english.stackexchange.com/questions/58921/does-hes-mean-both-he-is-and-he-has)

• how about ``ìt```?

• shouldn't the negative contractions be handled here too?
"cannot": ["can", "not"] is the only one.
But how about stuff like
"shouldn't": ["should", "not"]

This would affect logic_negate, I assume.

**Comment by spencermountain** [comment]
oooh, very nice find.
i guess we could figure it out by the next verb? is it just he's/she's/it's with this ambiguity?

**Comment by OS-Chris** [comment]
What about who, what, when, where, why & how ?
who is, who has....

**Comment by redaktor** [comment]
just btw: added this project to the corresponding awesomeness:
https://github.com/edobashira/speech-language-processing

**Comment by spencermountain** [comment]
figured out a solution for `he's, she's, it's, who's,what's,where's,when's,why's,how's`

it is 'is' unless the next verb is negative, then it's 'has'
will keep this open until I address "n't" properly.
thanks!
