### ISSUE TITLE
Changes in the fork and the pull request ...

### ISSUE THREAD

**Issue by redaktor** [spencermountain/nlp_compromise#42]
Hey,

just commited nearly the last changes to the fork
https://github.com/redaktor/nlp_compromise
before I could do a pull request.

I need to eliminate the
• 'hardcoded' dups in lexicon generation
• last 37/1360(?) tests failing

The lexicon will be at least 10% smaller then and I really think starting with this structure 
language dependent contributing can become easy.
Just because I saw you were recently active ...

**Comment by spencermountain** [comment]
hey yeah, can you make smaller pull requests?
i'm a bit worried about some compression strategies making things less readable/maintainable.
I guess it's a trade-off, but should be discussed.
and yeah, i'm not ready for adding multiple-languages into the api yet.
looks like neat work.
-spence

**Comment by spencermountain** [comment]
two things: 
i've been thinking about using browserify, instead of all the node-specific export stuff 
This would let us get rid of lots of that cruft.

second, i guess removing quotes off some properties would reduce filesize, I forget how 'proper' that is, and if we're supposed to do that or not. it's fine by me if it doesn't introduce any issues.

thirdly, ;)  pretty sure " and ' are both one character, of same filesize, if that's what you're up do.

love the namespacing of ./index, etc. please make prs for those things
cheers

**Comment by redaktor** [comment]
thirdly, ;) pretty sure " and ' are both one character, of same filesize, if that's what you're up do.

> absolutely not - that is just a linter doing it - it is more a typographic aspect.
I think they are better readable. Apart from that following
https://github.com/airbnb/javascript#strings

About the compression stuff.
It would be easy to change the factory stuff so that just the minimized client-side gets
compressed by replacing.
All the characters for replacing are 1 byte. None of them has to be escaped or a special meaning in regexes ...

**Comment by spencermountain** [comment]
yeah, is there a way to only do the compression like that on the client-side?
..short of a client-side gzip?

**Comment by redaktor** [comment]
absolutely. I'll have a look in an hour. 
It was written from scratch. It will go to grunt.
I think the replacing is different from gzip. While no code can run before unzipped (at least without AMD), the uncompressing will take place after the page is there and while a possible writer thinks about his first word.

**Comment by redaktor** [comment]
> yeah, is there a way to only do the compression like that on the client-side?

• only for nlp.min.js
• only running ```grunt```

will now also build all detected languages ('possibleLanguages')...
**done**

**Comment by spencermountain** [comment]
hey so i just figured out browserify, which handles 'require' nicely on the clientside. it means no more concatenation of files, which means we don't need closures and stuff. it's pretty cool.

do you have any ambitions to get some of these changes back into this project? right now, your branch is 20 ahead, and 20 behind... 
is grunt doing zip when it builds? that's clever.

**Comment by redaktor** [comment]
Well, theoretically it is 20 behind. Practically it is just 2 behind (your commits #40 and #41  – and I am doing them now). 
Unfortunately github is not as clever as humans and can't detect when a change you made in between was merged to my "different structure".

Give me some hours and I could comment it better - unfortunately I have to drive to Hamburg now 
(3 hours).

Regarding browserify:
My friends are the people behind [dojo](http://dojotoolkit.org) and the Dojo Foundation Project [requireJS](http://requirejs.org). They were there first and I think they are the good.

In _build.js it is just about ten lines to "extend" all node requires to dojo requires ...
I think it is easier and cooler than browserify and does the same.
Read also: https://www.sitepen.com/blog/2014/09/09/on-yui-dojo-2-and-javascript-toolkits/
See also other parts of the dojo universe, e. g. https://www.sitepen.com/about/labs.html

**Comment by redaktor** [comment]
... the nlp.min.js is now 12% smaller while maintaining readability in modules.

Regarding AMD this is the shortest tutorial for
• confirming my view ;)
• showing the difference
http://blog.millermedeiros.com/amd-is-better-for-the-web-than-commonjs-modules/

Regarding dojo the documentation is here
http://dojotoolkit.org/documentation/#modules

But I would provide a demo anyway.

I would suggest to have all 3 options:
• browser one-concat-file (useful for newbies drag 'n drop and quick testing, as it is)
• browser or node.js amd (an "interplanetary" dojo module) *
• node.js require (as it is)

*) the same module can be used in browser or node.js amd environments - clever
apart from the browser works e.g. in the redaktor boilerplate (node.js)

But still 26 tests fail (most of them are minor, 2 are bugs).
I would
• correct them
• and do #40 and #41

And then basically **everything** could be pull requested in a squashed commit.
The other languages could basically go in other dictionary files (maintained wherever, by us if you want).
They could also be pushed to git + npm as nlp_compromise-contrib-german or so ...
I have no idea how to separate it to smaller commits because all changes are basically only
in the 3 dictionary files, the _build and the Gruntfile.
The other changes made are when referencing these (and adapting your changes inbetween).


--- btw:
Regarding grunt-uglify I found an issue
WARN: Side effects in initialization of unused variable verbs [nlp.zip.js:363,4]
The variable is assigned to ```window``` but grunt-uglify simply does not check this...

The "Dropping unused variable" will be fixed now...

**Comment by spencermountain** [comment]
hey Sebastian, just to be clear, I'm not going to merge this pull request, if you make it.
You gotta keep them small, and re-architecting requires planning+coordination. I'm not ready to support other languages, and i'm worried about further-compressing to obfuscate the dictionaries.
i'm pretty open to collaboration, but needs planning of this scale.
Break it into smaller ones?
fwiw, EVERY file has changed since you branched, so git would never be able to handle this merge.

**Comment by redaktor** [comment]
Sorry,
I don't get it (?)

> I'm not ready to support other languages

This would mean we can just maintain our own fork because the changes in the data part
were contributed in the issues and you merged them.

> i'm worried about further-compressing to obfuscate the dictionaries

Nothing is compressed or obfuscated, only the client_side nlp.min.js (but isn't that the "goal" of this file?)

> EVERY file has changed since you branched, so git would never be able to handle this merge.
??? Have you noticed I made a new fork on 28th?
Since then these are the changes:
https://github.com/spencermountain/nlp_compromise/compare/master...redaktor:master

Let's break it down:
Let's analyse the files mentioned before in the [fork](https://github.com/redaktor/nlp_compromise)
Let's have a look into the src/data folder:
The folders "en" and "lexicon" are NOT needed and completely optional for github.
("phrasal verbs" in "lexicon" is a next TODO for me).
However - these folders *and all its contents* are automatically created by running ```> grunt```
The same is for the folder "client_side".

So the only files in "data" are the "dictionary..." files and the "_build" task and these files did not exist before.
These are 34 optional/new/auto-created and thus not needed files.
They replace 17 old 'static' files.
80-34-17 = 29 files changed. We only discuss these changes , right?

Now let's git diff at the folders "methods" and "parents":
parents has 17 files, methods 6 files and the src 4 files.
That is 27 files where some data ("word content") moved to the new dictionary files and some references to node modules changed off course. Nothing else changed here (?).
So 27+2 is 29 and the 2 are
unit_tests (where I maybe added some comments) and the Gruntfile itself off course.

**Comment by redaktor** [comment]
Maybe I missed anything. But the idea was that if you add any "language" key to the dictionary (even if it is just one)
```> grunt``` would do the rest
Let us say we add to JJ
```
{..., de: 'toll'}
```
```> grunt``` would make a "de" folder with the contents it can.

(I need to add the rest of rules to dictionary_rules to make it complete ...)

A practical example what I'll do afterwards:
The University of Cologne has more than 50% of the german regexes/rules as MIT.
Our database has a translation of all of your words in different languages as MIT.
It would insert ```de```to the dictionary and after adding the rules I just need to
write the rest of the rules and run
```> grunt```

**Comment by spencermountain** [comment]
yeah, `80-34-17 = 29`, you gotta make it easier on me. Just break it into smaller, cleaner PRs, explaining the benefit of each one. I love your help with this project, big time. Just follow the pull request etiquette.

Alternatively, I could make a german repo, I could add you as admin, and we could blast away - prefer that?
cheers
-spence

**Comment by redaktor** [comment]
just btw:
There is a nice new grunt task for babeljs.io : 
https://github.com/babel/grunt-babel

> Turn ES6 code into vanilla ES5 with no runtime required using babel

I wonder if that means we can write native Javascript modules today and just grunt
I mean https://github.com/airbnb/javascript#modules which have the same effect than dojo modules but they are coming with ES6 ...

**Comment by spencermountain** [comment]
yeah, totally. i don't know a lot about this stuff, but maybe we'd also get a speed-boost using the new Map objects, instead of regular {}?  definitely worth checking out, I don't know what the compiled es5 looks like, it could be really huge?
i'm not too picky about babel/browserify doing the 'require' bit. either's good.
-spence

**Comment by redaktor** [comment]
yeah. However just wanted to mention that I merged the last of your changes in the 'single' commit https://github.com/redaktor/nlp_compromise/commit/5be7208cb950c840edbd923c0797c5ee9525112a (I skipped grunt, this is just to explain) - as you can see we already have the nouns.pps referenced_by used already build by '_dictionary.js'.
There is no need to list this words again here, so I basically did your changes but replaced the "words" by the ("shared") module nouns ...
That is what flexibility by modularity means, I think:
You would need to change 2 files for the whole project in the end but it generates (now) 34 modules

**Comment by redaktor** [comment]
Note: There are (the last) 2 tests failing. The logic here does not "match" the changed structure.
Please see https://github.com/spencermountain/nlp_compromise/blob/73520773d6c35a9bbe7d7dbbbd698aa1e1c0f54c/src/parents/verb/conjugate/verb_irregulars.js
The conjugation of ```be``` is listed twice.
[
```js
  [
      "be",
      "_ing",
      "was",
      "is",
      ""
  ],
```
...
```js
  [
      "be",
      "am",
      "was",
      "am",
      ""
  ]
```
]
This is a bit confusing. However I could add one of the conjugations 'manually'.
Just to let you know.

**Comment by spencermountain** [comment]
yeah, noticed that. maybe it deserves a special case in conjugate.js.

**Comment by redaktor** [comment]
```
test.deepEqual(negate("he may go to the store"), "he may not go to the store")
```
MD should behave like CP if it has no special case...
I'll do that now and then I could start submitting (nicely packed) ...

**Comment by redaktor** [comment]
@spencermountain 
I am done now with the changes, just the browserify-Gruntfile and your last unit_tests ... 
Although the complete separation of program logic and data logic is not totally complete, 
I think now could be a good moment to start contributing it.
It has just to be done as logical as possible -

How about the following procedure ?:
1.
There are 3 important _dictionary files in src/data and they are new:
_dictionary.js
= all words
_dictionaryNames.js
= named entities
_dictionaryRules.js
= word- and verb-rules and regexes

2.
The Gruntfile
Running grunt would create 
34 files in a folder /en in ./data
This includes a helpFns.js grouping twice or more declared functions.
The other data modules are optimized for modularity and to avoid any duplicates.

3.
The files in /parents and /methods (now referencing the new modules)

4.
The 17 old modules not needed anymore ...

---
browser filesize -14% and better overall performance.

• We just need to change 3 possible files in the end to change anything or add new languages and run grunt.
• Adding of new features would be the same as it is now, just with program logic and data logic separated.
• But this makes adding of languages a fluid and easier process.

**Comment by spencermountain** [comment]
hey man, github won't even display this diff, this thing is way too gnarly to get merged. 
I've been clear, adding more languages is not about just changing the dictionary/rules, each if statement is making an assumption on english. Dude, If you want to make changes, you're gonna need to make a way(!) smaller request. The grunt-zip idea sounds interesting. I'm receptive if it reduces client-side filesize, while keeping the data pretty human editable.

**Comment by redaktor** [comment]
But the if statements will become the "rest of the rules" in dictionary_rules. We already have a partial german "version" 
- wait it is not a "version" - since you can just do nlp.setLang('de') but I thought it would be to complicated to introduce it for now.
The above procedure step 3 could be in "per file"-requests but the other 3 could not without breaking anything (including client) ...
