### ISSUE TITLE
referenced_by and reference_to 

### ISSUE THREAD

**Issue by redaktor** [spencermountain/nlp_compromise#45]
Hey,
please see https://github.com/spencermountain/nlp_compromise/blob/master/src/parents/noun/index.js

```referenced_by``` uses the ```var posessives``` (typo ?). It is defined in the scope of the module and is
```
{
    "his": "he",
    "her": "she",
    "hers": "she",
    "their": "they",
    "them": "they",
    "its": "it"
  }
```

while ```reference_to``` uses the var ```var possessives``` defined in the scope of the function which is just
```
{
    "his":"he",
    "her":"she",
    "their":"they"
}
```

Shouldn't both be the same and maybe
```
{ 
    mine: 'i',
    yours: 'you',
    his: 'he',
    her: 'she',
    its: 'it',
    our: 'we',
    their: 'they',
    them: 'they' 
}
```
?

**Comment by spencermountain** [comment]
hey, so I've added     
    "mine": "i",
    "yours": "you",
    "our": 'we',
they're still not working though, can you look at it?

**Comment by redaktor** [comment]
Hm,
in the fork it seems to work. Could you add some tests ?
