### ISSUE TITLE
Circa, or c.

### ISSUE THREAD

**Issue by franciscop** [spencermountain/nlp_compromise#47]
Is it possible to add an exception for the following regex?

    /c\.(\ ?[0-9]+)/

Right now I'm using a small script to pre-process the text that I want to analyze with nlp_compromise. The current solution that I am using looks like this:

    raw = raw.replace(/c\.(\ ?[0-9]+)/g, 'circa $1');

Basically, any `c. YEAR` will be replaced by `circa YEAR` so nlp doesn't mess up with that `c.`. While only `c.` might not be good enough to be added to [abbreviations](https://github.com/spencermountain/nlp_compromise/blob/master/src/data/lexicon/abbreviations.js) since it's not significant enough, this expression matches `c. NUMBER`, which I think it's unambiguous enough. What do you think? Is there a way to add this or other similar, case-specific abbreviations?

(I am not proposing to change c. for circa, this is just my solution, I am proposing to add, if possible, an exception for `c. YEAR` and not break sentences in that period).

**Comment by spencermountain** [comment]
ah, of course. great idea.
will add it this afternoon. thanks!

**Comment by redaktor** [comment]
when it comes to years:
as a good christian ;) may I also ask how to deal with b.c. or a.d. years (historic publications).

**Comment by spencermountain** [comment]
i think bc and ad are supported, even in the date parser, but I will check.

**Comment by franciscop** [comment]
Thank you @spencermountain . There are few [similar things to circa in wikipedia](https://en.wikipedia.org/wiki/Circa) which would benefit from this:

    c.
    ca.
    circ.
    cca.

This could be done [with this regex](https://regex101.com/r/aN6jZ1/1):

    /(cca|circ|ca|c)\.\ ?[0-9]+/g

Note: inverse order for better matching. Also, there's a small test to make sure that `CA. 1954` is not matched, as CA could be California.

**Comment by franciscop** [comment]
About other, I completely agree with a.d. and b.c., I didn't encounter them in the texts I am parsing but I think they could also be treated in a similar way.

**Comment by spencermountain** [comment]
so the list of supported abbreviations is in [./data/abbreviations](https://github.com/spencermountain/nlp_compromise/blob/master/src/data/lexicon/abbreviations.js)
and [./methods/sentence.js](https://github.com/spencermountain/nlp_compromise/blob/master/src/methods/tokenization/sentence.js)

the idea being that the ones in abbreviations.js are all nouns, and the ones in sentence.js aren't.
but my feeling is it's far from complete. I'll leave this open, can you guys hunt for more?
cheers

**Comment by spencermountain** [comment]
there's a great list in freeling's data package. I'm gonna diff with ours, then i'll close this issue
