### ISSUE TITLE
ngram: support for ngrams with size equal to 1

### ISSUE THREAD

**Issue by nitaku** [spencermountain/nlp_compromise#50]
Currently there is no way to use nlp.ngram() to perform a simple word frequency calculation (i.e. ngrams with size equal to one). Setting the max_size option to 1 produces ngrams with size 2. Setting max_size to 0 also gives the same result. I suspect that these two are the lines responsible for this issue: https://github.com/spencermountain/nlp_compromise/blob/master/src/methods/tokenization/ngram.js#L11 (where max_size is incremented - why?) and https://github.com/spencermountain/nlp_compromise/blob/master/src/methods/tokenization/ngram.js#L6
 (where since 0 is false, max_size is assigned the value 5).

**Comment by spencermountain** [comment]
hey Matteo, you just want a word-frequency calculation? I think ngram is much a different concept then. That task is much simpler:
```
"this is text".split(' ').reduce(function(h,w){h[w]=(h[w]||0)++; return h}, {})
```
good luck!

**Comment by nitaku** [comment]
Thank you for your help (and for your awesome library)! I wanted to use your ngram function because it seemed to me that it also cleans up the text from punctuation etc.
I understand that a proper ngram should be more than one word, but I got confused trying to achieve this result (and by the fact that calling the function with max_size=2 returns ngrams with size<=3 (!), including the ngrams with size=1 which I desperately wanted :) ).
I managed to solve my issue by modifying my copy of the library, but please tell me if I am missing something.

**Comment by redaktor** [comment]
Hm, the only bug I can find is that it returns ngram up to a ```max_size``` ```+1``` .
This is due to the summing up before line 37.
Change line 37 to (instead '<=')
```js
for (k = 1; k < max_size; k++) {
```

> but I got confused trying to achieve this result

I don't get the point.
When you change the line above and comment out the last lines in ngram.js - isn't this the output?

```
[ [ { word: 'really', count: 2, size: 1 },
    { word: 'think', count: 2, size: 1 },
    { word: 'all', count: 2, size: 1 },
    { word: 'i', count: 1, size: 1 },
    { word: 'that', count: 1, size: 1 },
    { word: 'we', count: 1, size: 1 },
    { word: 'it\'s', count: 1, size: 1 },
    { word: 'good', count: 1, size: 1 } ],
  [ { word: 'really think', count: 2, size: 2 },
    { word: 'i really', count: 1, size: 2 },
    { word: 'think that', count: 1, size: 2 },
    { word: 'that we', count: 1, size: 2 },
    { word: 'we all', count: 1, size: 2 },
    { word: 'all really', count: 1, size: 2 },
    { word: 'think it\'s', count: 1, size: 2 },
    { word: 'it\'s all', count: 1, size: 2 },
    { word: 'all good', count: 1, size: 2 } ],
  [ { word: 'i really think', count: 1, size: 3 },
    { word: 'really think that', count: 1, size: 3 },
    { word: 'think that we', count: 1, size: 3 },
    { word: 'that we all', count: 1, size: 3 },
    { word: 'we all really', count: 1, size: 3 },
    { word: 'all really think', count: 1, size: 3 },
    { word: 'really think it\'s', count: 1, size: 3 },
    { word: 'think it\'s all', count: 1, size: 3 },
    { word: 'it\'s all good', count: 1, size: 3 } ],
  [ { word: 'i really think that', count: 1, size: 4 },
    { word: 'really think that we', count: 1, size: 4 },
    { word: 'think that we all', count: 1, size: 4 },
    { word: 'that we all really', count: 1, size: 4 },
    { word: 'we all really think', count: 1, size: 4 },
    { word: 'all really think it\'s', count: 1, size: 4 },
    { word: 'really think it\'s all', count: 1, size: 4 },
    { word: 'think it\'s all good', count: 1, size: 4 } ],
  [ { word: 'i really think that we', count: 1, size: 5 },
    { word: 'really think that we all', count: 1, size: 5 },
    { word: 'think that we all really', count: 1, size: 5 },
    { word: 'that we all really think', count: 1, size: 5 },
    { word: 'we all really think it\'s', count: 1, size: 5 },
    { word: 'all really think it\'s all', count: 1, size: 5 },
    { word: 'really think it\'s all good', count: 1, size: 5 } ] ]
```

**Comment by nitaku** [comment]
@redaktor Yes, the modification you described is what I did in my local copy of nlp.js, sorry if I explained it poorly. The only difference with my code is that I enabled a way to "force" the ngram function to compute ngrams of size = 1 only (I wanted a quick&dirty way of computing word frequencies, and I wanted to take advantage of the ability of nlp.js to get rid of punctuation and complex spacing).

**Comment by spencermountain** [comment]
thanks guys, fixed the off-by-one bug for max_count. maybe ngram should be a method on `Section` and/or `Sentence`, so that it's built inline with punctuation and spacing fixes... and capitlisation.... and conjugation!?
oooh!

**Comment by nitaku** [comment]
Thanks to you! :) Now it's working great.
About having ngram as a method on `Section` and `Sentence`... that would be really nice! :D
