### ISSUE TITLE
PP - compared to fork

### ISSUE THREAD

**Issue by redaktor** [spencermountain/nlp_compromise#53]
Hey,
sorry for opening a new one (trying to separate the different questions) :
This is about posessive-pronouns```PP``` which were not covered in the initial comparison (same reason: because they split to different categories in our db - I made the db compatible now, when you look for PP it'll join all 3 categories) - I am pasting the question I just added to the code (not sure if there are better expressions for the cases):
```js
	// TODO - this covers more than the original :
	// posessive-pronouns (should) have 3 forms :

	// as possessive (adjective) determiner pronoun (my) OR
	// as possessive (noun) pronoun (mine) OR
	// as a reflexive pronoun (myself)
```

What do you think?

btw: some changes you proposed in contributing.md also came to the fork.
E. g. it has now JSdoc documentation (WIP, standard template for now) ...

**Comment by spencermountain** [comment]
yeah, i agree. her/she/hers could be subclassed as different pronoun types.

especially as PP are now really important with the references, reference_to methods.
are there any grammatical differences that pos.js should know?

is the best way then, for me to cherry-pick changes from your fork into this? i could add your name on the readme somewhere.

**Comment by redaktor** [comment]
It would be so helpful if you could tell me what is not cherry in the fork.
It would not be about my name at all (I am doing a completely open source decentralized network called "redaktor" behind the stage to save the world.media one day) - so yes it would be nice if you would add "redaktor" then.
Let me outline the goal of the fork again (I know there is still lots of work to do and I can't do it 100% of the time) :
We will have 3 "dictionaries" (for words, names and rules).
We will have a build tool to write all the data modules (if wanted in different languages, if not, not). It is written like a framework, we just need to change the dictionary files and run grunt.
Each generator will *be able to* get an array of 12 language-customized syllables to make compression for the minified client file even easier.
(Do not wonder if any .min file appears by running the _build tool, they'll be cleaned by grunt in the end - for now we are just working in /src).
While separating the rest we are strongly working on the "this" so that the whole project can make use of a consistent options and cache and helpers/factory functions. This can lead to much more performance and reduce the code significantly.

Maybe you got me wrong - our usual rule says "if possible always push to [your project]" - so again:
It would be helpful to know what is not cherry...

If I would to pull requests I would make a fresh fork and try to submit them as small as possible and well commented. I would not mind if you'd reject some. But it would be most fruitful for further committing if we could have the same structure regarding the modules.
Do you think anything is wrong here ? (It is easy to change that in _build) ...

Just tell me what we can do better... You click the button we do the rest.

**Comment by spencermountain** [comment]
thanks man, I really appreciate the work you're been doing. What's the project you're working on? I'd love to know more.

Honestly, I don't mind which changes are made too much, as long as I understand what it's doing. I think even in the medium-term we'd be glad about separating different languages into separate projects. Every language is just so prickly, non-generic, and shares barely any grammar rules among them all - there's right-to-left, gendered verbs, conjugated nouns, etc. I could perhaps be swayed with the right demo, but I think we'd be better-off.

yeah, i would prefer definitely prefer smaller PRs on a fresh fork. I don't have any changes planned in the next few weeks, so it's all yours. The zip stuff is cool, the helper method stuff is cool, the cache stuff is super-cool (if a little scary?) and just explain the ideas in the PR. No one understands the project like you do, so my trust is great.
cheers
