### ISSUE TITLE
Question - Advanced Date Parsing

### ISSUE THREAD

**Issue by silentrob** [spencermountain/nlp_compromise#57]
First off, this is such a great project! 
Do you have any thoughts returning an array of dates from a parsed sentense? Or more advanced logic like ranges?

It looks like this does a lot of what Ive done in https://github.com/silentrob/normalizer but I suspect much faster (basic normalization and commonwelth => american conversation). 

I also have some code that deals with numbers and parsing math expressions here https://github.com/silentrob/superscript/blob/master/lib/math.js.

**Comment by spencermountain** [comment]
hey Rob! nice to meet you. I'm a huge fan of phonegap, and your work is really cool. We should collaborate on this commonwealth-american stuff, immediately. I've done a really poor job, and it's an immediately solvable, and useful problem.
i have ambitions to re-write the whole library actually. There's an enormous amount of work to do.
With all the babel/esX/typescript stuff that's been happening this year, there's a million ways to do a better job at this in 2015-6. Wanna join?

**Comment by silentrob** [comment]
Wow, thanks for the warm reply. 
Im courious to know what you are planning for your V2 branch. My hands are pretty bloody with other NLP projects. (nl-tools, natural, lemmer, normalizer, qtypes, and some POS stuff ) I was hoping your library would let me depricate them all :)

I've still got some work to do in https://github.com/silentrob/superscript, but I really would like to rip out the core piece and use nlp_compromise, hopefully removing some other slower depenancies too. 

I would love to help pitch in if there are any free cycles or I suspect Ill bump into some issues as they crop up and I can commit that back.

**Comment by redaktor** [comment]
Again : This is all done in the fork. 
@silentrob : if you need it now, see http://github.com/redaktor/nlp_compromise/ .
You can see the commit messages, I did not find the time to document the various new methods.
I think the translation of values for "machines" is important and meanwhile I also wrote the detection of more than 80 units for Cardinal Value Parsing.
And I am nearly done with a money/currency parser which makes the values complete.
I did not make the browserify changes yet. So it is node only. But I would do it now if anybody needs it.
For the fork:
E.g. a quick test
```js
var nlp = new NLP();
var val = nlp.value("possible travel dates are 25th of June, 12-21-2015 or 12/23/2015 - and now I eat minus three bananas while driving sixty km/h during the next twenty nine months.");
var date = val.date({now: new Date()});
var nr = val.get('number');
var speed = val.get('speed');
console.log( 'VALUE:',util.inspect(val,{depth:null}) );
console.log( '---' );
console.log( util.inspect(date,{depth:null}) );
console.log( util.inspect(nr,{depth:null}) );
console.log( util.inspect(speed,{depth:null}) );
```
-->
```js
VALUE: { input: 'possible travel dates are 25th of June, 12-21-2015 or 12/23/2015 - and now I eat minus three bananas while driving sixty km/h during the next twenty nine months.',
  numeric: 'possible travel dates are 25th of June, 12-21-2015 or 12/23/2015 - and now I eat -3 bananas while driving 60 during the next 29 months.',
  numbers: [ { text: 'minus three', number: -3 } ],
  dates: 
   [ { text: '25th of June',
       relativeTo: false,
       day: 25,
       month: 6,
       year: false,
       weekDay: false,
       Date: Thu Jun 25 2015 02:00:00 GMT+0200 (CEST),
       localized: 'Thursday, June 25, 2015' },
     { text: 'next twenty nine months',
       relativeTo: Sat Aug 15 2015 09:46:35 GMT+0200 (CEST),
       day: 15,
       month: 8,
       year: 2015,
       weekDay: 6,
       Date: Sat Aug 15 2015 02:00:00 GMT+0200 (CEST),
       to: 
        { text: 'next twenty nine months',
          day: 15,
          month: 1,
          year: 2018,
          weekDay: 1,
          Date: Mon Jan 15 2018 01:00:00 GMT+0100 (CET) },
       localized: 'Monday, January 15, 2018' },
     { text: '12-21-2015',
       relativeTo: false,
       day: 21,
       month: 12,
       year: 2015,
       weekDay: 1,
       Date: Mon Dec 21 2015 01:00:00 GMT+0100 (CET),
       localized: 'Monday, December 21, 2015' },
     { text: '12/23/2015',
       relativeTo: false,
       day: 23,
       month: 12,
       year: 2015,
       weekDay: 3,
       Date: Wed Dec 23 2015 01:00:00 GMT+0100 (CET),
       localized: 'Wednesday, December 23, 2015' } ],
  values: 
   [ { category: [ 'quantity' ],
       quantity: -3,
       numeral: 'minus three',
       input: 'minus three',
       context: false },
     { category: [ 'speed', 'velocity' ],
       quantity: 60,
       numeral: 'sixty',
       input: 'sixty km/h',
       context: 
        { prefix: 'k',
          prefixText: 'kilo',
          toSI: { by: 1000, plus: 0, base: 'm' },
          unit: 'm',
          unitExpo: false,
          unitText: 'meter',
          category: [ 'length' ],
          system: 'metric',
          input: 'kilometer',
          by: false,
          per: 
           { prefix: false,
             prefixText: '',
             toSI: { by: 3600, plus: 0, base: 's' },
             unit: 'h',
             unitExpo: false,
             unitText: 'hour',
             category: [ 'time' ],
             system: 'metric',
             input: 'hour',
             by: false } } } ] }
// ---
// ...
```

**Comment by silentrob** [comment]
I saw that fork, but didn't know it was the next version. This is super cool, and immensely more powerful. I could invision the same api being used to resolve pronouns too `.val({'it': 'bike', 'he': 'Billy'})`

**Comment by redaktor** [comment]
My plan was to create a multilanguage .js or JSON style dictionary for rules and content which comes for example with a web interface like https://translate.adobe.com/adobe and maybe with db support.
This can be used in any .js project dealing with 'language'.
>> I could invision the same api being used to resolve pronouns too .val({'it': 'bike', 'he': 'Billy'})
this would be cool.
To be concrete: the currency parser is a bit complicated, but nearly done and in general I need to document it ;) and related to your idea
it is also a TODO for me to add a 'of' to quantity (which adjective and noun belongs to quantity) and
to reflect the whole thing in .pos.
btw everyone: I've never tried https://togetherjs.com - have you?
how about a nlp hackathon in the future ?

**Comment by spencermountain** [comment]
yeah, i agree we should push this forward to the next level together.
i drank coffee last week and wanted to do a re-write using es6 classes, for word methods, & typescript for bug-reduction. I too, love the work you've done with the date/value parser

**Comment by redaktor** [comment]
:+1: Especially for typescript - then it would fit perfectly into our system !!! !
The whole dojo community is moving to typescript but because I am still 'learning' I hesitated to mention it ;) et. al.: 
@SitePen has cool typescript projects like https://sitepen.github.io/mayhem/guide and tutorials :
https://www.sitepen.com/blog/2013/12/31/definitive-guide-to-typescript/
https://www.sitepen.com/blog/category/typescript/

**Comment by silentrob** [comment]
So Im a fan of both Typescript (type checking) and no es6/es7 features. I'm not confinced you need both to achieve better bug reduction. I think using es6 with babel and having really good eslint rules will probably catch most things. Then rely on regression tests. I noticed lots of commented out examples on the bottom of files, these would all make good regression tests.

I'm still working though the code (in redaktor/fork) and digging how the dictionatyRules are setup. I guess for me the question comes down to what exactly the projects goals are. My first thought was;
1. Client Side NLP Parsing. (sub 100K file)
2. 80+% coverage of english in terms of count.

But what about features?
POS, NER (names and orginazations?)
Date Parsing
Light NLU?

I think I saw stemming but no lemmatizing. 
Basic verbs are there but do we have enough coverage? See https://github.com/silentrob/tense
On the nlu side are things like basic arithmetic in the vision or outside? I'm doing some of that here, https://github.com/silentrob/superscript/blob/master/lib/math.js#L88-L153

Sorry if this thread has become more than an issue. Happy to chat in another medium. (GH, IRC, Skype, Call etc)

**Comment by spencermountain** [comment]
hey, great!
I've given you both write access. let's throw some ideas into a branch. check out some work i've started in the v2 branch https://github.com/spencermountain/nlp_compromise/tree/2.0
feel free to just commit straight to there, if you'd like. 

I'm not sensitive either about using any particular technology. The only goals being that it's light-weight enough to have 80%ish accuracy in the browser. Happy about adding new features too, just as long it remains a cute plug-and-play lib.

I thought it would be smart to have all our generic methods hang on a Word class, and a Noun class that inherits methods from Word, etc. That would be a huge win, in itself.

Sebastian and I have discussed supporting other languages, which I'm still a bit scared of.

**Comment by spencermountain** [comment]
I know it's a weird statement, but I found moving existing methods into type-annotation to be insanely therapeutic. it's like.. less .. fear-based.. how you don't need to worry about weird null values all the time. I tried a few atom/grunt workflows but am completely open-minded about how we decided to code/compile this, just as long as we're on the same page. I'm sure there's some clever ways.

let's do an irc channel, I'll make one on freenode or whatev

**Comment by spencermountain** [comment]
http://webchat.freenode.net/?channels=%23nlp_compromise&uio=Mj10cnVlJjk9dHJ1ZSYxMD10cnVlJjExPTIyNiYxND1mYWxzZQf4

**Comment by silentrob** [comment]
I also have an open slack channel on superscript. More then welcome to hangout there too.

**Comment by spencermountain** [comment]
that work with you Sebastian?
https://superscriptjs.slack.com/messages/nlp_compromise/

**Comment by redaktor** [comment]
basically yes - it says
> To start using Slack, you'll need to be invited by your team administrator.
the address would be api a_t redaktorcms.com ...

**Comment by redaktor** [comment]
@silentrob you wrote:
> I'm still working though the code (in redaktor/fork) and digging how the dictionatyRules are setup. I guess for me the question comes down to what exactly the projects goals are.

• All the 'dictionary' files can be in a db, a REST API or as they are. They are totally optimized for reading and translating and they generate all the data folders with minified / compressed files for the browser
• They come with a build tool which is src/data/_build
to build for now use it e. g. in the console from the data folder like
```
node _build -l
```
--> in the future this will be included simply in ```grunt```

**Comment by kristoferjoseph** [comment]
![mj-popcorn](https://cloud.githubusercontent.com/assets/76308/9503595/c88e9666-4bec-11e5-91bd-90f2ffa1d957.gif)
