### ISSUE TITLE
"something" and "other" not labelled as nouns

### ISSUE THREAD

**Issue by Undeterminant** [spencermountain/nlp_compromise#58]
I'd consider these words common enough to be included in the lexicon.

**Comment by spencermountain** [comment]
hey claire, thanks for the input. They're both in there.
something is a "possessive pronoun"
https://github.com/spencermountain/nlp_compromise/blob/d4feb704d3e7ae527566cc12dc14af01679e8798/src/data/lexicon.js#L245
other is
other is an adjective
https://github.com/spencermountain/nlp_compromise/blob/master/src/data/lexicon/adjectives.js#L684
cheers

**Comment by Undeterminant** [comment]
Oh, weird. One of the demos is out of date, then.

http://rawgit.com/spencermountain/nlp_compromise/master/client_side/cute_demo/index.html

**Comment by spencermountain** [comment]
this is possible. just updated them. which sentence was it?

**Comment by Undeterminant** [comment]
I was testing in the JavaScript console because I wanted to see the results of calling functions without installing the library in Node. :)

Running `nlp.pos('something').tags()[0][0]` gives me `"PP"` now; seems fixed.
