### ISSUE TITLE
2.0 - just a note : string to regex

### ISSUE THREAD

**Issue by sebilasse** [spencermountain/nlp_compromise#59]
see lexidates:
res.dayS = '\b('.concat(Object.keys(res.days).join('|'), ')\b');

When a string becomes a regex, in javascript, you must quote stuff with special regex-meaning double.
So ```\b``` should be ```\\b```here - see my original code...

If you want to use it like on top you need to pass it to a quote function, e.g.
Mozilla:
```js
function escapeRegExp(string){
  return string.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "\\$1");
}
```
or in dojo see [.string](https://github.com/dojo/core/blob/a3fc92a4a5bd4d0f632b30644166c7f1bb823c06/src/string.ts) ...

**Comment by silentrob** [comment]
Good catch, I have something simular in superscript. We can wrap that easy enough.

**Comment by spencermountain** [comment]
hey seb, thanks, i moved this around. I also used a lot of your units & values work.
2.0 is nearly ready, give it a crack if you want. I'll probably release it this week, will you check it out?
