### ISSUE TITLE
Implementing the package on a data structure ? 

### ISSUE THREAD

**Issue by haraldur12** [spencermountain/nlp_compromise#66]
Hey I am quite new to meteor and computer science basically. I am linguistic trying to learn computational linguistics somehow. I guess I am struggling still. I was wondering how it would be possible to use this on my own corpus ? Let's say that I have a list of sentences and whenever I choose the sentence I want to see the properties of the sentence. Would be possible ?

**Comment by spencermountain** [comment]
hey there, welcome to computer science!
```
var my_corpus="Tony Danza is dancing. He is nice."
var sentences= nlp.pos(my_corpus).sentences;
console.log('sentence 1 properties:')
console.log(sentences[0])
console.log('sentence 2 properties:')
console.log(sentences[1])
```
hope it helps,

**Comment by haraldur12** [comment]
the problem is unfortunately it is not just one sentence but the whole book. Would I be able to define var as my mongo db and tell it to get all the data from it ? Thanks for the reply!

**Comment by spencermountain** [comment]
yeah, if your text is in mongodb, you'll need to fetch it. Then it
shouldn't matter if it's a book or a single sentence.
good luck!

**Comment by haraldur12** [comment]
I am feeling so lame ahah. I couldn't implement the package in to the meteor templates argh.

**Comment by haraldur12** [comment]
Template.SentenceNLP.events = function() {

var my_corpus = Sentences.find.currentSentenceId
var sentencer=  nlp.pos(my_corpus) ;

	"click #nlp-pos": function(e,t) {
	 e.preventDefault();

	return nlp.pos(my_corpus);
});

I tried to use that one but however I am getting unexpected token. I want my web corpus page to be like that of the "long_demo" so that whenever I am seeing a new sentence I just can just click on the buttons and mark them up. What am I missing ?

**Comment by spencermountain** [comment]
keep trying!

**Comment by spencermountain** [comment]
how'd it go?
