### ISSUE TITLE
Does not work in a web worker

### ISSUE THREAD

**Issue by PalmerAL** [spencermountain/nlp_compromise#72]
I'm trying to use nlp_compromise in a Web Worker, but trying to use any of the nlp methods results in an "nlp is not defined" erorr. The problem is that there is no ```window``` object in a web worker, so https://github.com/spencermountain/nlp_compromise/blob/master/index.js#L49 does not export anything.  Something like this might work instead:

		if (typeof window === "object" || typeof DedicatedWorkerGlobalScope === "function") {
			self.nlp = nlp;
		}

**Comment by spencermountain** [comment]
hey! very neat! wanna make a pr? Sounds like a cool project.

**Comment by spencermountain** [comment]
btw, i'm a week or two from releasing a major 2.0 update. It's on the branch '2.0', if you wanted to start using it. Either way, i'll include this change there too
cheers

**Comment by PalmerAL** [comment]
Hmmm, I was going to add the fix to 2.0, but I can't seem to get the build to work. ```grunt build``` works fine, but running the demos gives an "nlp is not defined" error (this is without any changes), and running the tests gives this:

```
>> Local Npm module "grunt-contrib-connect" not found. Is it installed?

Running "mochaTest:test" (mochaTest) task
>> Mocha exploded!
>> Error: Cannot find module '../../src/term/noun/noun.js'
>>     at Function.Module._resolveFilename (module.js:337:15)
>>     at Function.Module._load (module.js:287:25)
>>     at Module.require (module.js:366:17)
>>     at require (module.js:385:17)
>>     at Object.<anonymous> (/Users/username/Documents/nlp_compromise/tests/unit_tests/nouns/nouns.js:4:12)
>>     at Module._compile (module.js:435:26)
>>     at normalLoader (/Users/username/Documents/nlp_compromise/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
>>     at Object.require.extensions.(anonymous function) [as .js] (/Users/username/Documents/nlp_compromise/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:311:12)
Warning: Task "mochaTest:test" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.

```

**Comment by spencermountain** [comment]
ah, sorry. maybe it's too rough yet.
added your condition to v1 and v2. should be up on nlp_compromise@1.1.5
let me know if it works?

**Comment by PalmerAL** [comment]
Yes, it works now. Thanks!
